[project]
name = "x402"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "erik", email = "erik.reppel@coinbase.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "httpx>=0.28.1",
    "pydantic>=2.11.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
