[project]
name = "x402"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "erik", email = "erik.reppel@coinbase.com" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
