name: Publish x402 base package to NPM

on:
  workflow_dispatch:
  pull_request:
    # No path restrictions - run on all PRs

jobs:
  publish-npm-x402:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'npm' || '' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
          cache-dependency-path: ./typescript
      
      - name: Install and build
        working-directory: ./typescript/packages/x402
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
      
      - name: Publish x402 package
        working-directory: ./typescript/packages/x402
        run: |
          # Get package information directly
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          
          echo "Package: $PACKAGE_NAME@$PACKAGE_VERSION"
          
          # Check if running on main branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Publishing to NPM (main branch)"
            pnpm publish --provenance --access public
          else
            echo "Dry run only (non-main branch: ${{ github.ref }})"
            pnpm publish --dry-run --no-git-checks
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_X402 }}
